name: CI pipeline
run-name: ${{ github.actor }} lets do this 

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: print a message
              run: echo "Hello, world!"
            
            - name: checkout code
              uses: actions/checkout@v2

            - name: setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
            
            - name: Clean and reinstall dependencies
              run: |
                rm -rf node_modules
                npm install
            
            - name: run test
              run: npm test

            - name: run ESLint
              run: npm run lint

    delivery:
      runs-on: ubuntu-latest
      needs: build
      if: success()
      steps:
        - uses: actions/checkout@v4
          with:
            token: ${{ secrets.ACCESSS_TOKEN }}

        - name: set up Git
          run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            
        - name: merge to main   
          run: |
            git fetch
            git checkout main
            git pull
            git merge develop --allow-unrelated-histories --no-edit
            git push origin main
